### ISSUE TITLE
Testing checklist

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-geostats#4]
- [x] Gzipped mbtiles
- [ ] Non-gzipped mbtiles
- [x] MBTiles with features
- [x] MBTiles without features
- [x] GeoJSON with features
- [ ] GeoJSON without features (blocked by https://github.com/mapnik/mapnik/issues/3463)
- [x] Shapefile with features
- [x] Shapefile without features
- [x] CSV with features
- [x] CSV without features
- [x] `null` values (see #3)
- [x] Mixed type values
- [x] Boolean values
- [x] String values
- [x] String values with more than 256 characters
- [x] Number values
- [x] Non-primitives (which mapnik coerces into strings)
- [x] Attributes with over 100 unique values
- [x] Attributes with over 1000 unique values
- [x] Layers with other 100 unique attributes
- [x] Layers with over 1000 unique attributes
- [ ] More than 100 layers
- [ ] More than 1000 layers
- [x] `options.attributes`
- [x] Invalid file format
- [x] Invalid GeoJSON
- [x] Invalid Shapefile
- [x] Invalid MBTiles
- [x] Invalid CSV
- [x] Invalid filePath to MBTiles
- [x] Invalid filePath to other file (Mapnik-interpreted)
- [x] All geometry types

**Comment by davidtheclark** [comment]
Unchecked boxes each have their own issue now: #8, #20, #21, #22. So closing this issue.
